version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - db_data:/var/lib/mysql
      - ${SQL_INIT_DIR}/script_201801719.sql:/docker-entrypoint-initdb.d/script_201801719.sql

  api:
    image: node:18-alpine
    container_name: api_service
    working_dir: /app
    volumes:
      - ./api:/app 
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      API_KEY: ${API_KEY}
    command: ["sh", "-c", "npm install && node index.js"]
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: ${GF_SERVE


percentage_used": 85,
asks": [
{
  "pid": 1,
  "name": "systemd",
  "state": 1,
  "user": 0,
  "ram": 12,
  "father": 0
},
{
  "pid": 2,
  "name": "kthreadd",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 0
},
{
  "pid": 3,
  "name": "rcu_gp",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
}
}

{
  "pid": 4,
  "name": "rcu_par_gp",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 5,
  "name": "slub_flushwq",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 6,
  "name": "netns",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 7,
  "name": "kworker/0:0",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 8,
  "name": "kworker/0:0H",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 9,
  "name": "kworker/u4:0",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 10,
  "name": "mm_percpu_wq",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 11,
  "name": "rcu_tasks_rude_",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 12,
  "name": "rcu_tasks_trace",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 13,
  "name": "ksoftirqd/0",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 14,
  "name": "rcu_sched",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 15,
  "name": "migration/0",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 16,
  "name": "idle_inject/0",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 17,
  "name": "kworker/0:1",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 18,
  "name": "cpuhp/0",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 19,
  "name": "cpuhp/1",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 20,
  "name": "idle_inject/1",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 21,
  "name": "migration/1",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 22,
  "name": "ksoftirqd/1",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 23,
  "name": "kworker/1:0",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 24,
  "name": "kworker/1:0H",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 25,
  "name": "kdevtmpfs",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 26,
  "name": "inet_frag_wq",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 27,
  "name": "kauditd",
  "state": 1,
  "user": 0,
  "ram": null,
  "father": 2
},
{
  "pid": 28,
  "name": "kworker/1:1",
  "state": 1026,
  "user": 0,
  "ram": null,
  "father": 2
},