services:
  db:
    image: ezapeta/mysql_custom:8.0
    container_name: mysql_db
    env_file:
      - .env
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  api:
    image: ezapeta/api_custom:18-alpine
    container_name: api_service
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./api:/app 
    ports:
      - "5000:4000"
    depends_on:
      - db
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data: