services:
  agente:
    image: ezapeta/agente_custom:golang
    container_name: 'agente_go'
    restart: always
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - /proc:/proc
      - /etc/passwd:/etc/passwd
    pid: host
    user: root
    privileged: true
    ports:
      - '5200:5200'